[toolchain]

[features]
seeds = false
skip-lint = false

#[programs.localnet]
#battleboosters = "9DZTGocMWp5n7nH9dfN4VMxhDoZuN82AAsne4qcaWygJ"

[programs.devnet]
battleboosters = "AYsivJpxmwVfeUaBWg7FZt4MDatg2myKCSS52UTCDXeS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/0xantman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
