[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
battleboosters = "9JyF2qTLYfEyy7UVSPVNCQQgUD4AQ5u5gVdGmAZu7cPA"

[programs.devnet]
battleboosters = "9JyF2qTLYfEyy7UVSPVNCQQgUD4AQ5u5gVdGmAZu7cPA"

[programs.testnet]
battleboosters = "9JyF2qTLYfEyy7UVSPVNCQQgUD4AQ5u5gVdGmAZu7cPA"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/programs/metadata.so"


[test.validator]
url = "https://api.devnet.solana.com"
#ledger = ".anchor/test-ledger"

## SOL/USD mainnet pyth
#[[test.validator.clone]]
#address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
## Mainnet Switchboard SOL/USD program
[[test.validator.clone]]
address = "GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR"

#Randomness
[[test.validator.clone]]
address = "SBondMDrcV3K4kxZR1HNVT7osZxAHVHgYXL5Ze1oMUv"

[[test.validator.clone]]
address = "zL8xj8TfQewdL1JmBfagYJydEsdgUZLnTvGhtewrjog"
[[test.validator.clone]]
address = "7Gs9n5FQMeC9XcEhg281bRZ6VHRrCvqp5Yq1j78HkvNa"
[[test.validator.clone]]
address = "9tMV6o14dJH95PoRgQHhGYMiyLbVS39HPqHWQ5hD4Vn1"
[[test.validator.clone]]
address = "FqVyQbsS7YE5WsPWQ5xEukFWjJyjiRtJMgg64tuBuRRU"
[[test.validator.clone]]
address = "FqVyQbsS7YE5WsPWQ5xEukFWjJyjiRtJMgg64tuBuRRU"

[[test.validator.clone]]
address = "ChtPnhtm152NwS5ULDSE9emajj7CLr2bC1eiNpkEMjck"

[[test.validator.clone]]
address = "5Qv744yu7DmEbU669GmYRqL9kpQsyYsaVKdR8YiBMTaP"

[[test.validator.clone]]
address = "SysvarS1otHashes111111111111111111111111111"

#[[test.validator.account]]
#address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
#filename = "tests/accounts/pythSolUsdAccount.json"

# Solana Randomness Service
[[test.validator.clone]]
address = "RANDMo5gFnqnXJW5Z52KNmd24sAo95KAd5VbiCtq5Rh"

# Sbv3 Program ID
[[test.validator.clone]]
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

# Sbv3 ProgramStateAccount
[[test.validator.clone]]
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"

# Sbv3 IDL
[[test.validator.clone]]
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/0xantman/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000
shutdown_wait = 2000

