pub const MY_APP_PREFIX: &[u8] = b"BattleBoosters";
pub const PROGRAM_STATE: &[u8] = b"program";
pub const EVENT: &[u8] = b"event";
pub const FIGHT_CARD: &[u8] = b"fightCard";
pub const RARITY: &[u8] = b"rarity";
pub const MINT_AUTHORITY: &[u8] = b"mintAuthority";
pub const MINT: &[u8] = b"mint";
pub const STALENESS_THRESHOLD : i64 = 300;
pub const SOL_USD_FEED_DEVNET: &str = "GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR";
